#print("How old are you?", end=' ')
#age = input()
#print("How tall are you?", end=' ')
#height = input()
#print("How much do you weigh?", end=' ')
#weight = input()
#print(f"So, you're {age} old, {height} tall, and {weight} heavy.")
#print("Let's try something else.")
#name = input('What do they call you? ')
#print(f"{name}? That's a weird name.")

age = input("How old are you? ")
height = input("How tall are you? ")
weight = input("How much do you weigh? ")

print(f"So, you're {age} years old, {height} tall, and {weight} lbs heavy.")
